name: Build Crate and Run Example Tests

on:
  push:
  pull_request:

jobs:
  check-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build crate and run nextest
        run: nix run .#build-and-test
      - name: Run examples, as integration tests
        run: nix run .#run-examples
